FROM node:22.20.0-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy source code
COPY . .

# Create logs directory
RUN mkdir -p logs

# Expose port (adjust if needed)
EXPOSE 5001

# Start the application
CMD [ "npm", "start" ]